# Generated by Django 4.1.6 on 2023-04-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_author_post_avatar_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name=100)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
